spring.mongodb.uri=mongodb+srv://rishikjariwala54_db_user:vRJi57R2ZoPSs58f@cluster0.ekgttjl.mongodb.net/JournalingApp?retryWrites=true&w=majority&appName=Cluster0
spring.mongodb.auto-index-creation=true
spring.application.name=JournalingApp